services:
  - type: web
    name: skin-cancer-linebot
    env: python
    plan: free
    pythonVersion: 3.11  # ระบุเวอร์ชัน python เป็น 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
